[profile.default]
solc = "0.8.24"
evm_version = "cancun"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
]
libs = ["node_modules", "lib"]
